<!--
#### Preamble ####
# Purpose: Testing Data from the Toronto Paramedic Service
# Prerequisites: Need to have downloaded the data using [inputs/data/data_import.qmd]
# Author: Sebastian Rodriguez
# Email: me@srod.ca
# Date: 3 February 2023
# GitHub: https://github.com/seb646/toronto-paramedic-responses
-->
---
title: "Testing Data from the Toronto Paramedic Service"
format: html
author: "Sebastian Rodriguez"
---
```{r}
#### Workspace set-up ####
library(tidyverse)
library(janitor)
library(here)
library(readr)
```

```{r}
# Fetch the .csv file created from Open Data Toronto's "Land Ambulance Response Time Standard" package: https://open.toronto.ca/dataset/land-ambulance-response-time-standard
raw_response_data <- readr::read_csv(here::here("inputs/data/raw_response_data.csv"), show_col_types = FALSE) |>
  clean_names() |>
  filter(performance_in_percentage != "NA")

# Test that the target performance is less than or equal to 75%
raw_response_data$plan_in_percentage |> max() <= 0.75

# Test that the reported year is greater than or equal to 2013
raw_response_data$response_time_standard_year |> min() >= 2013

# Test that the actual performance data is less than or equal to 100%
raw_response_data$performance_in_percentage |> max() <= 1.00

# Test that the actual performance data is greater than or equal to 0%
raw_response_data$performance_in_percentage |> min() >= 0.00

```

```{r}
# Fetch Open Data Toronto's "Pre-Hospital Emergency Care Performance Metrics" package:  https://open.toronto.ca/dataset/pre-hospital-emergency-care-performance-metrics
raw_emergent_care_data <- readr::read_csv(here::here("inputs/data/raw_emergent_care_data.csv"), show_col_types = FALSE) |>
  clean_names()

# Test that the reported year is greater than or equal to 2014
raw_emergent_care_data$year |> min() >= 2014

# Test that the actual responses is a number
raw_emergent_care_data$actual |> class() == "numeric"

# Test that the actual responses is not greater than Toronto's population
raw_emergent_care_data$actual |> max() <= 3000000

# Test that the actual responses is not 0 
raw_emergent_care_data$actual |> min() >= 0
```

```{r}
# Fetch Open Data Toronto's "Paramedic Services Incident Data" package: https://open.toronto.ca/dataset/paramedic-services-incident-data
raw_incident_data <- readr::read_csv(here::here("inputs/data/raw_incident_data.csv"), show_col_types = FALSE) |>
  clean_names()

raw_incident_data

# Test that the units arrived on scene is not greater than the city's number of paramedics
raw_incident_data$units_arrived_at_scene |> max() <= 1186

# Test that the units arrive on scene is greater than zero
raw_incident_data$units_arrived_at_scene |> min() >= 0

# Test that the dispatch time is a date 
raw_incident_data$dispatch_time |> class() == "POSIXct"

# Test that the incident type contains is comprised of characters
raw_incident_data$incident_type |> class() == "character"

```